### DISCUSSION TITLE
[Postgresql](Postgrex.Error) (undefined_column) Column typsend unknown

### DISCUSSION THREAD

**Discussion by BandanaPandey** [crate/crate#12184] [Q&A]
### CrateDB version

4.7

### CrateDB setup information

Number of nodes: 3
CRATE_HEAP_SIZE=2g

docker-compose.yml
```yaml
version: '3.3'
services:
  cratedb01:
    image: crate:latest
    ports:
      - "5432:5432"
      - "4201:4200"
    volumes:
      - /tmp/crate/01:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb01",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb02,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_nodes=3",
              "-Cgateway.recover_after_nodes=2"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g

  cratedb02:
    image: crate:latest
    ports:
      - "5433:5432"
      - "4202:4200"
    volumes:
      - /tmp/crate/02:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb02",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_nodes=3",
              "-Cgateway.recover_after_nodes=2"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g

  cratedb03:
    image: crate:latest
    ports:
      - "5434:5432"
      - "4203:4200"
    volumes:
      - /tmp/crate/03:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb03",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb02",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_nodes=3",
              "-Cgateway.recover_after_nodes=2"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g`
```

### Steps to Reproduce

Using Postgres Adapter to connect to elixir application.

1) Tried to run mix ecto.create 
with following configurations:
`config :crate_db_demo, CrateDbDemo.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "crate",
  database: "acqdat_core_dev",
  hostname: "localhost",
  port: 5432,
  pool_size: 10`

### Expected Result

Ideally it should works as specified here in this doc
https://crate.io/docs/crate/reference/en/4.7/interfaces/postgres.html

### Actual Result

But got error,
```15:39:03.425 [error] GenServer #PID<0.368.0> terminating
** (Postgrex.Error) ERROR 42703 (undefined_column) Column typsend unknown
    (db_connection 2.4.2) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

15:39:03.468 [error] GenServer #PID<0.376.0> terminating
** (Postgrex.Error) ERROR 42703 (undefined_column) Column typsend unknown
    (db_connection 2.4.2) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for CrateDbDemo.Repo couldn't be created: killed
```
