### ISSUE TITLE
Crate 3.3.5 - Unable to authenticate with IP-range

### ISSUE THREAD

**Issue by profijoeln** [crate/crate#10547]
**CrateDB version**:
Container image: crate:3.3.5
Image ID: docker-pullable://crate@sha256:79610eb88276d8434e58e7b456204fc796384cd4ecbc8efbd9d3c9fa2044faae

**Environment description**:
Ubuntu, Kubernetes worker
Cluster of 3 CrateDB nodes (replicas).

Configuration file 'crate.yaml' is made persistent, so that configuration changes persist over restarts. Using "path.conf=/persistentvolumepath"
Also data of the cluster is made persistent, so also set license persists over restarts.

**Problem description**:

After setting up auth configuration (and restarting for configuration to take effect), I try to login to admin UI with user 'crate'. Login window refreshes and logs show warning.

```
      1:
        user: crate
        address: 192.168.0.0/16
        method: trust
        protocol: http
```

```
[2020-09-16T09:31:29,324][WARN ][i.c.p.h.HttpAuthUpstreamHandler] [Stadelhorn] No valid auth.host_based.config entry found for host "192.168.101.92", user "crate", protocol "http"
[2020-09-16T09:31:29,331][WARN ][i.c.p.h.HttpAuthUpstreamHandler] [Stadelhorn] unauthorized http chunk
```

Having set address IP-range with method 'trust' I was expecting to gain access from 192.168.XXX.XXX. 
_Extra note: Access works when direct IP (192.168.101.92) is used, instead of IP-range (192.168.0.0/16)._

**Steps to reproduce**:

**1#** Set license to CrateDB

**2#** Edit crate.yml with following configuration (all nodes if using a cluster):

```
# Crate Configuration

network.host: _local_,_site_

# Paths
path:
  logs: /data/log
  data: /data/data
blobs:
  path: /data/blobs

auth:
  host_based:
    enabled: true
    config:
      0:
        user: readuser
        method: password
      1:
        user: crate
        address: 192.168.0.0/16
        method: trust
        protocol: http
```

**3#** Restart CrateDB for configuration to take effect.

**4#** Attempt login to CrateDB admin UI as user 'crate' with empty password.

_Note: In my deployment readuser is created. I do not know if this affects the results so I left it in._
