### ISSUE TITLE
HBA configuration is not picked up when ssl = on and keystore is configured

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#11489]
**CrateDB version**:

build from master branch

**Environment description**:

```
java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)

sw_vers
ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91
```

**Number of nodes: 3** (local instances bound to different virtual network interfaces)

Same config for all (except network.host)

```
# initial_master_nodes and discovery.seed_hosts are configured but not relevant to this issue

auth.host_based.enabled: true

auth:
  host_based:
    config:
      0:
        user: crate
        protocol: http
      4:
        protocol: transport
        ssl: on
        method: cert

ssl.transport.mode: on

#keystore is configured and picked up on startup, hasSSL is true in debugger
```

**Problem description**:

Error message is shown in logs` javax.security.sasl.AuthenticationException: No valid auth.host_based entry found for {node address}`

Details:
As mentioned [here](https://github.com/crate/crate/blob/d4eba8ec3bf0ee27ba972715a5702389dd2af5f4/server/src/main/java/io/crate/protocols/ssl/SslSettings.java#L72) "on" becomes "true" but it's compared with another enum value "on" [here](https://github.com/crate/crate/blob/388807579829bcdb2051532fe751f1ed574a7748/server/src/main/java/io/crate/auth/HostBasedAuthentication.java#L205) resulting to `isValidConnection` return false for valid entry. 

**Steps to reproduce**:

run cluster with configs shown above. Steps to configure keystore must be performed and reflected in config
