### ISSUE TITLE
Nodes don't use ssl when transport.mode is dual, keystore is configured

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#11514]
**CrateDB version:**

build from master branch

**Environment description:**

java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)

sw_vers
ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91

**Number of nodes: 2** (2 instances on same host)

HBA config for both nodes:

```
auth:
  host_based:
    config:
      0:
        user: crate
        address: _local_
        method: trust
      4:
        protocol: transport
        ssl: on
        method: cert
```
        
transport mode is dual on both nodes 

`ssl.transport.mode: dual`

keystore is configured according to [instructions](https://crate.io/docs/crate/reference/en/master/admin/ssl.html#admin-ssl)  

**Problem description:**
In debug mode, both nodes has message "`SSL Dual mode enabled, target node doesn't use SSL 127.0.0.1"` in logs.

[Logging of exception ](https://github.com/crate/crate/commit/363d4080e6fd2a348effdb8653e16216dd973f4e#diff-1c5d1afa88e5576595f2438652d0bc5bd960477875add1f6e0b6a06341765de1R89)during the dual probe handshake shows the following message: 
```
java.net.SocketException: Socket is closed
        at java.net.Socket.getInputStream(Socket.java:937) ~[?:?]
        at io.crate.protocols.ssl.ConnectionTest.probeDualMode(ConnectionTest.java:78) [crate-server.jar:?]
```
