### ISSUE TITLE
Allow specifying a role for limiting HBA configuration

### ISSUE THREAD

**Issue by proddata** [crate/crate#15466]
### Problem Statement

To enhance security in CrateDB clusters, we aim to tighten control over which users are allowed to use specific authentication modes. A challenge arises because users are often created during cluster operation, not during initial setup. Fortunately, with the introduction of roles and inheritance in CrateDB 5.6, we have a solution. We propose configuring HBA to allow access based on roles, rather than individual users. This approach is more flexible, accommodating users created post-setup.

Consider this example:

```sql
CREATE ROLE user_group1;
GRANT DQL TO user_group1;

CREATE USER user1 WITH (password='supersecret');
GRANT user_group1 TO user1;
```

In the HBA configuration, we would specify roles instead of individual users:

```
auth:
  host_based:
    config:
      0:
        user: crate
        address: _local_
        method: trust
      99:
        role: user_group1
        method: password
```

By doing so, we ensure that any user assigned to `user_group1` can authenticate using a password, streamlining the process and enhancing cluster security.
