### ISSUE TITLE
NPE on `MIN` aggregation on a mixed-version cluster 5.8.0/5.7.3

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#16361]
### CrateDB version

mixed 5.8.0 and 5.7.3, see below

### CrateDB setup information

docker-compose.yml:
```yml
x-services-volume:
  &services-volume
  type: bind
  source: ./jmx
  target: /jmx

services:
  cratedb01:
    image: crate/crate:5.7.3
    ports:
      - "4201:4200"
      - "7979:7979"
      - "8088:8080"
      - "5433:5432"
    volumes:
      - /tmp/crate/01:/data
      - *services-volume
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb01",
              "-Cdiscovery.seed_hosts=cratedb02,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=3",
              "-Ccluster.routing.allocation.disk.threshold_enabled=false",
              "-Cnode.attr.storage=hot",
              "-Cpath.repo=/tmp",
              "-Dcom.sun.management.jmxremote",
              "-Dcom.sun.management.jmxremote.port=7979",
              "-Dcom.sun.management.jmxremote.ssl=false",
              "-Dcom.sun.management.jmxremote.authenticate=false",
              "-Dcom.sun.management.jmxremote.rmi.port=7979"]
    deploy:
      resources:
        limits:
          cpus: "2"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
      - CRATE_JAVA_OPTS="-javaagent:/jmx/crate-jmx-exporter-1.0.0.jar=8080"
  cratedb02:
    image: crate/crate:5.8.0
    ports:
      - "4202:4200"
    volumes:
      - /tmp/crate/02:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb02",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=3",
              "-Ccluster.routing.allocation.disk.threshold_enabled=false",
              "-Cpath.repo=/tmp",
              "-Cnode.attr.storage=hot"]
    deploy:
      resources:
        limits:
          cpus: "2"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g

  cratedb03:
    image: crate/crate:5.8.0
    ports:
      - "4203:4200"
    volumes:
      - /tmp/crate/03:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb03",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb02",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=3",
              "-Ccluster.routing.allocation.disk.threshold_enabled=false",
              "-Cpath.repo=/tmp",
              "-Cnode.attr.storage=cold"]
    deploy:
      resources:
        limits:
          cpus: "2"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
```

### Problem description

@hlcianfagna discovered that a `MIN` aggregation throws an NPE.

The issue could *not* be reproduced on:
* 5.6.1 single node
* 5.8.0 single node
* 5.8.0 three nodes
* 5.7.3 three nodes

It was only observed on a setup with one node on 5.7.3 and two nodes on 5.8.0.

### Steps to Reproduce

```sql
create table demo (columna1 int primary key, columna3 object);

insert into demo (columna1, columna3) 
select 1,
$$
{
    "items": [
        {
            "snippet": {
                "publishTime": "2023-03-20T08:15:00Z"
            }
        }
    ]
}
$$;

with mis_items as(
  select unnest(columna3['items']) as un_item
  from demo
)
select min(un_item['snippet']['publishTime'])
from mis_items;
```

### Actual Result

```
java.lang.NullPointerException: Cannot invoke "io.crate.execution.engine.aggregation.AggregationFunction.newState(io.crate.data.breaker.RamAccounting, org.elasticsearch.Version, org.elasticsearch.Version, io.crate.memory.MemoryManager)" because "this.aggregations[i]" is null
	at io.crate.execution.engine.aggregation.AggregateCollector.prepareState(AggregateCollector.java:127)
	at io.crate.data.BatchIterator.collect(BatchIterator.java:226)
	at io.crate.data.BatchIterator.collect(BatchIterator.java:249)
	at io.crate.data.CollectingBatchIterator.lambda$newInstance$2(CollectingBatchIterator.java:87)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:146)
	at io.crate.execution.engine.distribution.DistributingConsumer.consumeIt(DistributingConsumer.java:129)
	at io.crate.execution.engine.distribution.DistributingConsumer.accept(DistributingConsumer.java:105)
	at io.crate.execution.engine.collect.CollectTask.lambda$new$0(CollectTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1570)
```

### Expected Result

A result set is returned.
