### ISSUE TITLE
Kubernetes Documentation - Volume Value Error

### ISSUE THREAD

**Issue by BrockSmedley** [crate/crate#5550]
https://crate.io/docs/scale/kubernetes/

**Problem description**:
```
volumes:
  - name: data
    hostPath:
        emptyDir:
            medium: "Memory"
```
should be
```
volumes:
  - name: data
    emptyDir:
        medium: "Memory"
```

A hostPath has to have a path; emptyDir here is an invalid value for hostPath. hostPath and emptyDir are separate volume types with different properties.
