### ISSUE TITLE
Kubernetes discovery plugin

### ISSUE THREAD

**Issue by bputt** [crate/crate#6153]
**Use case**: The documentation for deploying crate in kubernetes is a little outdated and doesn't work for newer versions of crate as ES removed the discovery type srv.

**Feature description**: Ideally, include a kubernetes discovery plugin out of the box. Is it possible to include the plugin from: https://github.com/fabric8io/elasticsearch-cloud-kubernetes

**Comment by bputt** [comment]
Currently using kubernetes 1.7 with docker 1.12 and here's the 2 configs

```
apiVersion: v1
kind: Service
metadata:
  name: crate-data
  labels:
    component: crate
    role: data
spec:
  ports:
  - port: 4300
    name: transport
  - port: 4200
    name: http
  selector:
    component: crate
    role: data
----
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cr-data
  labels:
    component: crate
    role: data
spec:
  serviceName: crate-data
  replicas: 2
  template:
    metadata:
      labels:
        component: crate
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: cr-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: crate:latest
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CRATE_HEAP_SIZE
          value: "512M"
        - name: EXPECTED_NODES
          value: "2"
        - name: CLUSTER_NAME
          value: "test-cluster"
        command:
          - /docker-entrypoint.sh
          - -Ccluster.name=${CLUSTER_NAME}
          - -Cdiscovery.type=srv
          - -Cdiscovery.srv.query=_cluster._tcp.crate-discovery.default.svc.cluster.local
          - -Cnetwork.host=0.0.0.0
          - -Cdiscovery.zen.minimum_master_nodes=1
          - -Cgateway.recover_after_nodes=2
          - -Cgateway.expected_nodes=${EXPECTED_NODES}
          - -Cnode.master=true
          - -Cnode.data=true
        ports:
        - containerPort: 4300
          name: transport
          protocol: TCP
        - containerPort: 4200
          name: http
          protocol: TCP
        volumeMounts:
        - name: crate-storage
          mountPath: /data/crate
      volumes:
      - name: crate-storage
        emptyDir: {}
```
