### ISSUE TITLE
Crate 3.0.6 on Kubernetes : not enough master nodes discovered during pinging

### ISSUE THREAD

**Issue by lparet-yseop** [crate/crate#7690]
**CrateDB version**: 3.0.6

**Environment description**: 

**Problem description**:

Maybe I'm doing things wrong maybe it's a bug... I don't really know. 

Trying to deploy CrateDB with Kubernetes, I created a CrateDB cluster with 3 nodes following this documentation: [RUN CRATEDB ON KUBERNETES](https://crate.io/docs/crate/guide/en/latest/deployment/containers/kubernetes.html)
I have only 1 Kubernetes master (who is node too) and 1 other node. 

Nodes are deployed but **they can't communicate**, I have this warning in loop on each node logs (docker logs <container_name>:
```
[2018-09-25T11:43:25,973][WARN ][o.e.d.z.ZenDiscovery     ] [Col Gentile] not enough master nodes discovered during pinging (found [[Candidate{node={Col Gentile}{PpUx-GfoT9Wk3jnuFXONuw}{TDpqxJwTTl6WPMqtzi9CJg}{PUBLIC_IP}{PUBLIC_IP:4300}{http_address=PUBLIC_IP:4200}, clusterStateVersion=-1}]], but needed [2]), pinging again
```

**Steps to reproduce**:

My configuration is like the documentation but I prefer put it mine here if something's bad

crate-controller.yml
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crate
spec:
  serviceName: "crate-set"
  replicas: 3
  selector:
    matchLabels:
      app: crate
  template:
    metadata:
      labels:
        app: crate
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: crate
        image: crate:3.0.6
        command:
          - /docker-entrypoint.sh
          - -Cnetwork.host=_eth0_
          - -Ccluster.name=${CLUSTER_NAME}
          - -Cdiscovery.zen.minimum_master_nodes=2
          - -Cdiscovery.zen.hosts_provider=srv
          - -Cdiscovery.srv.query=_crate-internal._tcp.crate-internal-service.${NAMESPACE}.svc.cluster.local
          - -Cgateway.recover_after_nodes=2
          - -Cgateway.expected_nodes=${EXPECTED_NODES}
          - -Cpath.data=/data
          - -Clicense.enterprise=false
        volumeMounts:
          # Mount the `/data` directory as a volume named `data`.
          - mountPath: /data
            name: data
        ports:
        - containerPort: 4200
          name: crate-web
        - containerPort: 4300
          name: crate-internal
        - containerPort: 5432
          name: postgres
        env:
        - name: CRATE_HEAP_SIZE
          value: "256m"
        - name: EXPECTED_NODES
          value: "3"
        - name: CLUSTER_NAME
          value: "my-crate"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
      volumes:
      # Use a RAM drive for storage which is fine for testing, but must
      # not be used for production setups!
      - name: data
        emptyDir:
          medium: "Memory"
```

crate-externale-service.yml
```
kind: Service
apiVersion: v1
metadata:
  name: crate-external-service
  labels:
    app: crate
spec:
  # Create an externally reachable load balancer.
  type: LoadBalancer
  externalIPs: 
  - PUBLIC_IP
  ports:
    # Port 4200 for HTTP clients.
  - port: 4200
    name: crate-web
    # Port 5432 for PostgreSQL wire protocol clients.
  - port: 5432
    name: postgres
  selector:
    # Apply this to all nodes with the `app:crate` label.
    app: crate
```

crate-internal-service.yml
```
kind: Service
apiVersion: v1
metadata:
  name: crate-internal-service
  labels:
    app: crate
spec:
  # A static IP address is assigned to this service. This IP address is
  # only reachable from within the Kubernetes cluster.
  type: ClusterIP
  ports:
    # Port 4300 for inter-node communication.
  - port: 4300
    name: crate-internal
  selector:
    # Apply this to all nodes with the `app:crate` label.
    app: crate
```

I start services and statefulset by running this command:
```
kubectl create -f "${SERVICE_NAME}.yaml" --namespace crate
```

I use Flannel for networking in Kubernetes.

Some command outputs:
```
kubectl get services --namespace=crate -o wide
```
| NAME   |      TYPE      |  CLUSTER-IP  | EXTERNAL-IP | PORT(S) |
|----------|:-------------:|------:|------:|------:|
| crate-external-service |  LoadBalancer | 10.106.57.171 | PUBLIC_IP | 4200:32712/TCP,5432:31742/TCP 
| crate-internal-service |    ClusterIP   |   10.96.84.169 | <none> | 4300/TCP

Tell me if you need more informations

Thanks in advance
