### ISSUE TITLE
create user from environment variable

### ISSUE THREAD

**Issue by bhagujava** [crate/crate#7888]
**Use case**:
Cratedb should have environment variable where we can directly add username and password just like postgresql.   

**Feature description**:
Lest assume we have write script for automation to make system up and running on one command. as per current documentation we have to connect cratedb using super user then we can add user manually ideally it should be automated if we pass environment argument along with grant permission.

For example

    crate01:
        image: crate
        container_name: crate01
        hostname: crate01
        volumes:
        - ~/volumes/demo//data/crate:/data
        ports:
        - "4200:4200"
        - "4300:4300"
        - "5432:5432"
        environment:
            CRATE_HEAP_SIZE: 1g
            CRATE_USER: admin
            CRATE_PASSWORD: admin
            CRATE_GRANT: all (dml,dql)
 

One more thing is there any way to give password to default user (crate) ?

**Comment by joemoe** [comment]
hi @bhagujava, thanks for your suggestion. this is a valid use case and we consider implementing this. i'll put that into the product process and keep you up to date. at the moment it is not possible to give a password to the crate user.

**Comment by mfussenegger** [comment]
We talked about this recently, and one question that came up is how this should behave in a clustered environment. For example, suppose:

```
crate01:
    ...
    environment:
        CRATE_HEAP_SIZE: 1g
        CRATE_USER: user1
        CRATE_PASSWORD: admin
        CRATE_GRANT: all (dml,dql)
crate02:
    ...
    environment:
        CRATE_HEAP_SIZE: 1g
        CRATE_USER: user2
        CRATE_PASSWORD: admin
        CRATE_GRANT: all (dml,dql)
crate03:
    ...
    environment:
        CRATE_HEAP_SIZE: 1g
        CRATE_USER: user2
        CRATE_PASSWORD: different_password
        CRATE_GRANT: all (dml,dql)
```


`crate02` and `crate03` define the same user, but different passwords. Which one would win? Would both `user1` and `user2` be created? Or would all users have to match?

One possible way to do this would be to just read the information on whatever node is elected as master node, and this node would:

- Create the user if it doesn't exist
- Set the password to the password in the env variable, independent of whether the user was created or not
- Set the privileges to the given privileges, also independent of whether the user was created or not

If the master changes, this logic would potentially be re-run

Another way would be to have each node execute the logic as part of the bootstrapping. That means they might override each other actions. Last one wins.

@chaudum I think this would also have been useful for your use-cases. Any inputs here?

**Comment by chaudum** [comment]
In the case of CrateDB Cloud we need to bootstrap multiple users. Them being bootstrapped by CrateDB itself would be great.

I thought, instead of having a single environment variable for username and password, defining the users as settings, much like the `auth.host_based.config.*` - but as cluster settings (not node settings).

For cluster settings the policy would be clear: https://crate.io/docs/crate/reference/en/latest/config/cluster.html#non-runtime-cluster-wide-settings But does it mean, that the settings from the elected master are applied?

Example of `auth.user.*` settings:

```yaml
auth:
  user:
    0:
      username: user0
      password: pw0
      privileges: all
    1:
      username: user1
      password: pw1
      privileges: dml,dql
...
```

I'm not sure if it worse, to have the password as cleartext in the settings, or as environment variable.
Of course, multiple users could also be achieved using environment variables, e.g.

```
CRATE_USERS_x_USERNAME: user
CRATE_USERS_x_PASSWORD: pw
CRATE_USERS_x_PRIVILEGES: ALL
...
```

You could then for example, in the Docker compose setup also combine env variables with settings:

```yaml
crate01:
    image: crate
    command: |
      crate -Dauth.user.0.username=admin -Dauth.user.0.password=${ADMIN_PASSWORD} -Dauth.user.0.privileges=all
...
    environment:
        - CRATE_HEAP_SIZE=1g
        - ADMIN_PASSWORD=s20RhAnQsDaRDI86
```
