### ISSUE TITLE
Data is not saving and lost after restart (docker, docker-compose up)

### ISSUE THREAD

**Issue by manveloff** [crate/crate#7960]
**CrateDB version**:
3.1.2

**Environment description**:
 - JVM version: "1.8.0_191
 - Kernel: Linux ac75a799d53e 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Distribution: CentOS-7
 - Docker: 18.09.0, build 4d60db4
 - 1 node, locally, using docker-compose up (not in swarm mode).

**Problem description**:

Data is not saving at all. That's a problem.

I start the app using docker-compose.yml and the command "docker-compose up".
CrateDB involved as one of services of the app (official docker image).
Everything works fine. Tables are creating. Data is adding.

In the docker-compose.yml I have a volume from my local filesystem to /data inside Crate's container.
Folders "data" and "logs" appears there. I can see a log file inside "logs". But the "data" folder is empty always. And when I restarted the app, all data is gone.

I don't know whether it's a bug or I'm doing something wrong. But I can't find any solution.

**Reproducing**:

Start the service using docker-compose.yml and the command "docker-compose up".
Write some data to the database.
Restart the service, data will gone.

**Comment by mfussenegger** [comment]
Sounds like a configuration issue of the volume mount. Could you post the `docker-compose.yml` contents?

**Comment by manveloff** [comment]
I was logging in to the Crate's docker container using "docker exec -it <container id> bash>, and saw:

```
/data
   logs/
   data/       - it was empty too
```

Here is my Crate's docker-compose.yml setup:
```
general-crate:
    image: crate/crate:latest
    ports:
      - 4200:4200
    environment:
      - CRATE_HEAP_SIZE=3g
    volumes:
      - /crate:/data
      - <path_to_the_project>/manager/configs/active/services/general-crate/crate.yml:/crate/config/crate.yml
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 2  
```
