### ISSUE TITLE
Query results in cluster crash

### ISSUE THREAD

**Issue by Crazy1van** [crate/crate#8718]
CrateDB version: 3.2.2

Environment description:
12 Nodes, each with 16 CPUs, 64GB RAM, 2GB SSD

When running certain types of queries on our cluster, we experience some sort of a crash.  Generally, the cluster becomes unresponsive within a few seconds of executing the query.  After a few minutes of the query running, the cluster reports job killed, then the web UI shows multiple nodes missing, lots of undereplicated data and shards.  The servers then appear to come back up and and it takes 15-30 minutes re-replicate the data.  We often end up with some tables with "missing shards".  Sometimes I have to manually restart crate on a server if it doesn't come back.

Query can be as "simple" as:

select field1, count(field2) from table1 group by field1, field2.

The tables we're querying contain a 1-3 billion rows, 50+ fields.  They are partitioned by day with 10 shards per partition and 1 replica each.  The servers only consume around 5-10% CPU while ingesting data.  If a query such as above is issued, the CPUs go to 100% on multiple servers and stay there until crash.

**Comment by mfussenegger** [comment]
Thank you for the report, could you provide some additional information:

1. Could you post your `crate.yml` - were there any changes to the circuit breaker settings?
2. How did you configure the heap size (`CRATE_HEAP_SIZE`)?
3. Are there any errors in the logs?
4. How is the cardinality of the columns you're grouping on?

**Comment by Crazy1van** [comment]
- All circuit breakers are left at default.
- I will check the logs to see if anything is still there and get back to you.
- Cardinality is fairly low.  Column 1 has roughly 188,000 possible values repeating over 2+ billion rows.  Column 2 has roughly 8,000 possible values repeating over those same 2+ billion rows.  The  resulting data set from grouping on the two columns should be less than 100 million rows.  We are actually trying to insert the result into another table (so no limit is used for the select queries.)  But even if running the select alone  with limit 100, it results in a long running process and crash.

**Crate.yml:**
```
license.enterprise: false 
cluster: 
  name: xxxxxxxx

node.name: "yyyyyyyy" 

bootstrap.memory_lock: true 

network.bind_host: _eth0_ 
network.publish_host: _eth0_ 

discovery.zen.minimum_master_nodes: 7 
discovery.zen.ping.unicast.hosts: 
  - 10.x.x.x:4300 
  - 10.x.x.x:4300  
  - 10.x.x.x:4300 
  - 10.x.x.x:4300  
  - 10.x.x.x:4300 
  - 10.x.x.x:4300 
  - 10.x.x.x:4300 
  - 10.x.x.x:4300 
  - 10.x.x.x:4300 
  - 10.x.x.x:4300 
  - 10.x.x.x:4300 
  - 10.x.x.x:4300 


gateway: 
  recover_after_nodes: 12 
  recover_after_time: 5m 
  expected_nodes: 12 

path.data: /cratedb/data
```

**Memory configuration:**

/etc/security/limits.conf 
```
crate soft memlock unlimited
crate hard memlock unlimited
root soft memlock unlimited
root hard memlock unlimited
```

/etc/sysconfig/crate
```
MAX_LOCKED_MEMORY=unlimited
CRATE_HEAP_SIZE=30500m
```
