### ISSUE TITLE
How to configure PostgreSQL OBCD Driver?

### ISSUE THREAD

**Issue by Georger2323** [crate/crate#8915]
I have a database on Crate DB. The database program is started through docker-compose.yml file. It is running on http://192.168.99.100:4200 (this is the docker machine's IP with the Crate's port)

I want to connect the Crate DB with Power BI. When I try to configure the PostgreSQL OBCD Driver, I don't know what to type on "Server" field.

So far I've tried "localhost", "127.0.0.1","0.0.0.0", "192.168.99.100" but none of these works.

So my question is, which IP address should I type on the "server" field?

![connectionError](https://user-images.githubusercontent.com/52736731/60949604-35d42800-a2fe-11e9-9fb9-f2f15616a5f1.png)

**Comment by mfussenegger** [comment]
Could you post your docker compose file/does it expose port 5432 as well?

Does `psql -h 192.168.99.100 -p 5432 -U crate` work?

If you can access `http://192.168.99.100:4200/` then using `192.168.99.100` in the server field should be correct.

**Comment by Georger2323** [comment]
Yes I can access http://192.168.99.100:4200/ as well as the rest of the programs that open up with the docker compose file.

I don't know the command that you are referring to since I'm using windows.

This is the docker-compose file:
[docker-compose.txt](https://github.com/crate/crate/files/3376387/docker-compose.txt)

**Comment by mfussenegger** [comment]
You'll have to add `5432:5432` to the ports:

```
  crate:
    image: crate:${CRATE_VERSION:-3.1.2}
    command: crate -Clicense.enterprise=false -Cauth.host_based.enabled=false
      -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    ports:
      - "4200:4200"
      - "4300:4300"
      - "5432:5432"
    volumes:
      - cratedata:/data
```

Grafana can access CrateDB because it has a `depends_on`, they connect via internal docker networking.

To expose ports outside so that you can access them from your host system the ports must be listed under ``ports``.
