### ISSUE TITLE
Type Serial not found

### ISSUE THREAD

**Issue by raspyweather** [crate/crate#9613]
**CrateDB 4.0.10**
**Environment description**:
Docker-Compose
```
version: '3'

networks: 
    crateDb_net:
        driver: bridge
volumes:
    crateDb_data:
        driver: local

services: 
    cratedb:
        image: crate
        volumes:
            - crateDb_data:/data
        ports:
            - 4200:4200
            - 5432:5432
        environment:
            - CRATE_HEAP_SIZE=2G
        command: "crate -Cnetwork.host=_site_ -Cnode.name=crate01 -Ccluster.initial_master_nodes=crate01 -Cgateway.expected_nodes=1"
```

 - Problem can be reproduced without docker: 
    - [x] yes
    - [ ] no -> Consider reporting the issue in https://github.com/crate/docker-crate instead
**Problem description**:

**Steps to reproduce**:

Execute 
```CREATE TABLE IF NOT EXISTS machineInfo (machineId serial, name string)``` will get you the error that it could not find the serial type. I couldn't find an auto increment type either. 
Is such a thing even possible with CrateDB or not?
